"""LLM-as-detector v2 — multimodal per-frame classification.

Pipeline:
    1. ffmpeg extracts audio track → mp3
    2. ffmpeg samples frames at regular intervals + supplemental frames around
       detected scene cuts (catches rapid events between sample points)
    3. whisper transcribes speech with word-level timestamps (cached)
    4. Single Gemini request per chunk containing:
         - Text prompt (vocabulary + instructions)
         - Full audio track inline
         - Speech transcript with word timestamps
         - Scene-cut list
         - N frame anchors, each labeled with its exact timestamp
    5. Model classifies mechanism firings PER FRAME using audio+speech+visual
       together. Timestamps are anchors we provide — never generated by the
       model (eliminates the drift seen in v1 video-upload pattern).
    6. Adjacent same-label frames are merged into LabelApplication ranges.

Why this design:
- v1 uploaded the full video and asked the model to invent timestamps for
  detected firings. The model's numeric output drifted (timestamps past
  video end, non-deterministic). v1 also hit frequent 503s on the video-
  analysis backend.
- v2 anchors every timestamp to a pre-extracted frame. The model's job is
  pure classification ("does mechanism X fire at THIS frame?") — not
  generation of numeric positions.
- Audio, speech, and scene structure are preserved so jump-scare-class
  content (where the audio sting IS the mechanism) still gets full signal.

Commercial-safe: Gemini API + ffmpeg + local Whisper. No TRIBE.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Optional

from feeling_engine.mechanisms.vocabulary import LabelApplication, MECHANISM_LABELS


GEMINI_MODEL_DEFAULT = "gemini-3-flash-preview"
# Note: gemini-2.5-flash is typically our preferred model but has been
# capacity-constrained (503) for this multimodal payload in recent tests.
# gemini-3-flash-preview handles the same payload cleanly; the frame-anchor
# architecture sidesteps 3-flash-preview's known timestamp-hallucination
# issue (we provide timestamps, model never generates them).
DEFAULT_SAMPLE_INTERVAL = 2.0             # seconds between base frame samples
DEFAULT_SCENE_THRESHOLD = 0.3             # ffmpeg scene-detect sensitivity (0-1)
DEFAULT_SCENE_SUPPLEMENT_WINDOW = 0.3     # seconds before/after each scene cut
DEFAULT_CHUNK_FRAMES = 40                 # frames per Gemini call
WHISPER_MODEL_NAME = "base"               # matches production/alignment.py

_LABEL_TIER: dict = {spec.name: spec.tier for spec in MECHANISM_LABELS}


# ─── ffmpeg / ffprobe helpers ────────────────────────────────────

def _probe_duration(video_path: Path) -> float:
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", str(video_path)],
        capture_output=True, text=True, timeout=30,
    )
    return float(r.stdout.strip()) if r.stdout.strip() else 0.0


def _strip_code_fences(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z0-9_-]*\n", "", text)
        if text.endswith("```"):
            text = text[:-3]
    return text.strip()


def _extract_audio(video_path: Path, cache_dir: Path) -> Path:
    """Extract audio track to mp3. Cached (invalidates if video newer)."""
    out = cache_dir / f"{video_path.stem}.mp3"
    if out.exists() and out.stat().st_mtime >= video_path.stat().st_mtime:
        return out
    cache_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y",
         "-i", str(video_path),
         "-vn", "-c:a", "libmp3lame", "-b:a", "128k",
         str(out)],
        check=True, capture_output=True, timeout=180,
    )
    return out


def _sample_frames_at_interval(
    video_path: Path, interval: float, cache_dir: Path,
) -> list:
    """Extract one frame every `interval` seconds via a single ffmpeg call."""
    frames_dir = cache_dir / "frames_base"
    frames_dir.mkdir(parents=True, exist_ok=True)
    for f in frames_dir.glob("frame_*.jpg"):
        f.unlink()
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y",
         "-i", str(video_path),
         "-vf", f"fps=1/{interval}",
         "-q:v", "4",
         str(frames_dir / "frame_%04d.jpg")],
        check=True, capture_output=True, timeout=600,
    )
    frames = []
    for fp in sorted(frames_dir.glob("frame_*.jpg")):
        m = re.search(r"frame_(\d+)\.jpg", fp.name)
        if not m:
            continue
        idx = int(m.group(1)) - 1   # ffmpeg numbers from 1
        ts = round(idx * interval, 3)
        frames.append((ts, fp))
    return frames


def _detect_scene_cuts(video_path: Path, threshold: float) -> list:
    """Return sorted scene-cut timestamps (seconds)."""
    r = subprocess.run(
        ["ffmpeg", "-v", "info",
         "-i", str(video_path),
         "-vf", f"select='gt(scene,{threshold})',showinfo",
         "-vsync", "vfr",
         "-f", "null", "-"],
        capture_output=True, text=True, timeout=300,
    )
    times = []
    for m in re.findall(r"pts_time:(\d+\.?\d*)", r.stderr):
        times.append(round(float(m), 3))
    return sorted(set(times))


def _extract_scene_cut_supplemental_frames(
    video_path: Path, cuts: list, window: float, cache_dir: Path,
) -> list:
    """Extract frames just before and just after each scene cut.

    Catches rapid events (e.g., jump-scare hard cuts) that happen between
    regular base-interval samples.
    """
    frames_dir = cache_dir / "frames_supp"
    frames_dir.mkdir(parents=True, exist_ok=True)
    for f in frames_dir.glob("frame_*.jpg"):
        f.unlink()
    duration = _probe_duration(video_path)
    frames = []
    for i, cut_t in enumerate(cuts):
        for offset_label, t in [("pre", cut_t - window), ("post", cut_t + window)]:
            if t < 0 or t > duration - 0.1:
                continue
            fp = frames_dir / f"frame_{i:04d}_{offset_label}.jpg"
            try:
                subprocess.run(
                    ["ffmpeg", "-v", "error", "-y",
                     "-ss", f"{t:.3f}",
                     "-i", str(video_path),
                     "-frames:v", "1", "-q:v", "4",
                     str(fp)],
                    check=True, capture_output=True, timeout=30,
                )
            except subprocess.CalledProcessError:
                continue
            if fp.exists():
                frames.append((round(t, 3), fp))
    return frames


def _merge_frame_lists(
    base: list, supplemental: list, dedupe_threshold: float = 0.5,
) -> list:
    """Combine frame lists; drop supplemental frames too close to a base frame."""
    base_times = [t for t, _ in base]
    merged = list(base)
    for t, fp in supplemental:
        if any(abs(t - bt) < dedupe_threshold for bt in base_times):
            continue
        merged.append((t, fp))
    merged.sort(key=lambda x: x[0])
    return merged


# ─── Whisper transcript ──────────────────────────────────────────

def _transcribe_with_whisper(
    audio_path: Path, cache_path: Optional[Path], verbose: bool,
) -> list:
    """Transcribe audio with word-level timestamps. Cached."""
    if cache_path and cache_path.exists():
        try:
            cached = json.loads(cache_path.read_text())
            if verbose:
                print(f"  whisper: cache hit ({len(cached)} words)", flush=True)
            return cached
        except Exception:
            pass

    if verbose:
        print(f"  whisper: transcribing ({WHISPER_MODEL_NAME} model)...",
              end="", flush=True)
    t0 = time.time()
    import whisper
    model = whisper.load_model(WHISPER_MODEL_NAME)
    result = model.transcribe(
        str(audio_path), language="en",
        word_timestamps=True, verbose=False,
    )
    words = []
    for seg in result.get("segments", []):
        for w in seg.get("words", []) or []:
            words.append({
                "word": str(w.get("word", "")).strip(),
                "start": round(float(w.get("start", 0)), 3),
                "end": round(float(w.get("end", 0)), 3),
            })
    if verbose:
        print(f" {len(words)} words in {time.time()-t0:.0f}s", flush=True)
    if cache_path:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        cache_path.write_text(json.dumps(words))
    return words


def _format_transcript_for_prompt(words: list) -> str:
    """Compact word-level transcript grouped by speech bursts."""
    if not words:
        return "(no speech detected)"
    lines = []
    buf: list = []
    buf_start = None
    last_end = 0.0
    for w in words:
        if buf_start is None:
            buf_start = w["start"]
        if w["start"] - last_end > 1.0 and buf:
            lines.append(f"[{buf_start:.1f}-{last_end:.1f}s] "
                         + " ".join(x["word"] for x in buf))
            buf = [w]
            buf_start = w["start"]
        else:
            buf.append(w)
        last_end = w["end"]
    if buf:
        lines.append(f"[{buf_start:.1f}-{last_end:.1f}s] "
                     + " ".join(x["word"] for x in buf))
    return "\n".join(lines)


# ─── Prompt + vocabulary ─────────────────────────────────────────

def _build_vocabulary_section() -> str:
    lines = []
    for spec in MECHANISM_LABELS:
        exemplar_str = "; ".join(spec.exemplars) if spec.exemplars else ""
        lines.append(
            f"- **{spec.name}** (tier {spec.tier}): {spec.phenomenology}"
            + (f". Examples: {exemplar_str}" if exemplar_str else "")
        )
    return "\n".join(lines)


_PROMPT_TEMPLATE = """You are a mechanism detector analyzing a {duration}-second {content_type}.

You are given a comprehensive multimodal input:

- Full audio track for the entire scene (music, silence, stings, breathing, SFX, speech)
- A word-level speech transcript with timestamps
- Scene-cut boundaries detected from shot changes
- N frame anchors — individual frames sampled from the video, each labeled with its exact timestamp

Your task: for EACH frame anchor, identify which mechanism labels fire at that specific moment. Use the audio at that timestamp, the speech around that time, the visual content of the frame, and the shot context together.

## The 28 mechanisms (fire ONLY from this vocabulary)

{vocabulary}

## Adjacent-label discrimination

Several labels are commonly confused. Before firing, consider the distinction:

- **body-surge vs satisfaction-peak**: body-surge is INVOLUNTARY shock (heart drops, startle response, physical jolt). satisfaction-peak is REWARD LANDING (the "yes!" moment, resolution, payoff).
- **anticipation vs restraint**: anticipation is FORWARD-LEANING. restraint is HOLDING-BACK.
- **pattern-break vs body-surge**: pattern-break is the STRUCTURAL surprise (expected pattern interrupted). body-surge is the BODY'S response. Both can fire at the same moment.
- **recognition vs evocation**: recognition is "I know this" (memory + familiarity). evocation is "this calls up a feeling" (memory + affect).
- **intimacy-turn vs vulnerability-transfer**: intimacy-turn is content MOVING TOWARD closeness. vulnerability-transfer is a speaker EXPOSING something that lands in listener.
- **drift vs restraint**: drift is ATTENTION SOFTENING. restraint is ATTENTION HELD BACK.
- **body-anchor vs body-turn**: body-anchor is SUSTAINED body presence. body-turn is the INITIATING moment.
- **release vs affect-fade**: release is the TENSION DROP after climax (breath out). affect-fade is emotion RETURNING TOWARD BASELINE.

## Intensity rubric

- 0.3 = barely perceptible
- 0.5 = clearly present to an attentive viewer
- 0.7 = strong, hard to miss
- 0.9 = overwhelming, moment-defining
- 1.0 = signature-level, canonical example

## Per-frame output — critical rules

For EACH input frame anchor, return 0 or more label firings (usually 0-3). The empty-labels case is CORRECT when no mechanism fires noticeably at this frame. Quality over quantity — fewer firings with solid multi-cue evidence beat many weak ones.

For each firing, include:
- "label": exact name from the vocabulary above
- "intensity": 0.0-1.0 per the rubric
- "confidence": 0.0-1.0
- "visual_cue": ONE sentence of specific visible evidence AT THIS FRAME
- "audio_cue": ONE sentence referencing the audio around this timestamp (music swell, silence, sting, breathing, SFX). Cite specific transcript words if speech-relevant.
- "prosodic_cue": ONE sentence on speech delivery at this moment, or "no speech"
- "contrast": ONE sentence — which adjacent label you considered and rejected

## Output format

Return JSON:
{{"frame_classifications": [
  {{"frame_index": N, "timestamp": X.X, "labels": [
    {{"label": "...", "intensity": 0.0, "confidence": 0.0,
      "visual_cue": "...", "audio_cue": "...", "prosodic_cue": "...", "contrast": "..."}}
  ]}}
]}}

One entry per input frame in order. The frame_index matches the order frames were provided (0, 1, 2, ...). No commentary outside JSON. No markdown fences.
"""


# ─── Gemini classification ───────────────────────────────────────

def _classify_frames_chunk(
    client, chunk_frames: list, audio_bytes: bytes,
    transcript_text: str, scene_cuts: list,
    content_type: str, duration: float, model: str,
    thinking_budget: int,
) -> tuple:
    """Classify one chunk of frames via a single Gemini request.

    Returns (entries, in_tok, out_tok) where entries is the list of
    frame_classifications from the model's JSON response.
    """
    from google.genai import types
    from feeling_engine._gemini_retry import gemini_with_retry

    prompt = _PROMPT_TEMPLATE.format(
        vocabulary=_build_vocabulary_section(),
        duration=f"{duration:.1f}",
        content_type=content_type,
    )
    scene_str = ", ".join(f"{c:.1f}s" for c in scene_cuts) if scene_cuts else "(none)"

    contents = [
        prompt,
        "\n## Full audio track (entire scene):",
        types.Part.from_bytes(mime_type="audio/mp3", data=audio_bytes),
        f"\n## Speech transcript (word-level):\n{transcript_text}",
        f"\n## Scene cuts detected at: {scene_str}",
        f"\n## {len(chunk_frames)} frame anchors to classify:",
    ]
    for idx, (ts, fp) in enumerate(chunk_frames):
        contents.append(f"\nFrame {idx} at t={ts:.1f}s:")
        contents.append(types.Part.from_bytes(
            mime_type="image/jpeg", data=fp.read_bytes(),
        ))
    contents.append("\nClassify each frame. JSON only.")

    # Horror / mortality content needs permissive safety settings
    safety = [
        types.SafetySetting(
            category=c,
            threshold=types.HarmBlockThreshold.BLOCK_ONLY_HIGH,
        )
        for c in (
            types.HarmCategory.HARM_CATEGORY_HARASSMENT,
            types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
            types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
            types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        )
    ]

    response = gemini_with_retry(
        client.models.generate_content,
        model=model,
        contents=contents,
        config=types.GenerateContentConfig(
            max_output_tokens=8000,
            thinking_config=types.ThinkingConfig(thinking_budget=thinking_budget),
            safety_settings=safety,
        ),
        verbose=False,
    )

    if not response.candidates:
        reason = getattr(response, "prompt_feedback", None)
        raise RuntimeError(f"Gemini blocked: {reason}")
    cand = response.candidates[0]
    if cand.content is None or cand.content.parts is None:
        finish = getattr(cand, "finish_reason", None)
        raise RuntimeError(f"Gemini empty response (finish={finish})")

    text = ""
    for part in cand.content.parts:
        if hasattr(part, "text") and part.text:
            text += part.text
    text = _strip_code_fences(text)
    parsed = json.loads(text)
    entries = parsed.get("frame_classifications", []) if isinstance(parsed, dict) else parsed
    if not isinstance(entries, list):
        raise ValueError("Expected frame_classifications array in response")

    usage = response.usage_metadata
    return entries, (usage.prompt_token_count or 0), (usage.candidates_token_count or 0)


# ─── Merge per-frame labels → LabelApplication ranges ────────────

def _clamp(v, lo: float = 0.0, hi: float = 1.0) -> float:
    try:
        x = float(v)
    except (TypeError, ValueError):
        return 0.5
    return max(lo, min(hi, x))


def _build_app(
    label_name: str, start_idx: int, end_idx: int, peak,
    frames: list, sample_interval: float, model: str,
) -> LabelApplication:
    start_ts = frames[start_idx][0]
    end_ts = frames[end_idx][0] + sample_interval
    peak_idx, _score, peak_data = peak
    intensity = _clamp(peak_data.get("intensity", 0.5))
    confidence = _clamp(peak_data.get("confidence", 0.5))
    visual = str(peak_data.get("visual_cue", "")).strip()
    audio = str(peak_data.get("audio_cue", "")).strip()
    prosody = str(peak_data.get("prosodic_cue", "")).strip()
    contrast = str(peak_data.get("contrast", "")).strip()
    parts = []
    if visual: parts.append(f"VISUAL: {visual}")
    if audio: parts.append(f"AUDIO: {audio}")
    if prosody: parts.append(f"PROSODY: {prosody}")
    summary = " | ".join(parts)
    return LabelApplication(
        label=label_name,
        tier=_LABEL_TIER[label_name],
        start_sec=round(start_ts, 3),
        end_sec=round(end_ts, 3),
        intensity=intensity,
        confidence=confidence,
        signals={
            "detector": "llm-gemini-v2",
            "model": model,
            "evidence": summary,
            "visual_cue": visual,
            "audio_cue": audio,
            "prosodic_cue": prosody,
            "contrast": contrast,
            "peak_frame_ts": round(frames[peak_idx][0], 3),
            "run_frames": end_idx - start_idx + 1,
        },
    )


def _merge_frame_labels_to_applications(
    classifications: list, frames: list, sample_interval: float, model: str,
) -> list:
    """Walk frames in order; group consecutive frames emitting the same label
    into a single LabelApplication. Peak frame (highest intensity*confidence)
    provides the evidence for the merged firing."""
    # Index frame_idx → list of per-frame label dicts
    by_idx = {}
    for entry in classifications:
        try:
            idx = int(entry.get("frame_index", -1))
        except (TypeError, ValueError):
            continue
        if idx < 0:
            continue
        by_idx[idx] = entry.get("labels", []) or []

    # Collect every label name seen at least once
    labels_seen = set()
    for lst in by_idx.values():
        for lbl in lst:
            name = str(lbl.get("label", "")).strip()
            if name in _LABEL_TIER:
                labels_seen.add(name)

    apps = []
    n_frames = len(frames)
    for label_name in labels_seen:
        run_start = None
        run_peak = None
        for i in range(n_frames):
            match = next(
                (l for l in by_idx.get(i, [])
                 if str(l.get("label", "")).strip() == label_name),
                None,
            )
            if match is not None:
                score = _clamp(match.get("intensity", 0.5)) * _clamp(match.get("confidence", 0.5))
                if run_start is None:
                    run_start = i
                    run_peak = (i, score, match)
                elif score > run_peak[1]:
                    run_peak = (i, score, match)
            else:
                if run_start is not None:
                    apps.append(_build_app(
                        label_name, run_start, i - 1, run_peak,
                        frames, sample_interval, model,
                    ))
                    run_start = None
                    run_peak = None
        if run_start is not None:
            apps.append(_build_app(
                label_name, run_start, n_frames - 1, run_peak,
                frames, sample_interval, model,
            ))
    apps.sort(key=lambda a: (a.start_sec, -a.intensity))
    return apps


# ─── Public API ──────────────────────────────────────────────────

def detect_from_video(
    video_path,
    model: Optional[str] = None,
    sample_interval: float = DEFAULT_SAMPLE_INTERVAL,
    scene_threshold: float = DEFAULT_SCENE_THRESHOLD,
    chunk_frames: int = DEFAULT_CHUNK_FRAMES,
    content_type: str = "movie scene",
    cache_dir: Optional[Path] = None,
    verbose: bool = True,
    thinking_budget: Optional[int] = None,
) -> list:
    """Detect mechanism firings via multimodal per-frame classification.

    Pipeline: audio extraction → dense frame sampling + scene-cut supplements
    → Whisper transcript → chunked Gemini classification → merge adjacent
    same-label frames into time ranges.

    Args:
        video_path: input video path.
        model: Gemini model (default gemini-2.5-flash).
        sample_interval: base frame sampling rate (seconds; default 2.0).
        scene_threshold: ffmpeg scene-detect threshold (0-1; default 0.3).
        chunk_frames: max frames per Gemini call (default 40).
        content_type: prose description for the prompt ("movie scene", "podcast", etc.)
        cache_dir: directory for caching audio/frames/transcript. Defaults to
            <video_parent>/cache/<video_stem>/.
        verbose: progress output.
        thinking_budget: Gemini thinking budget. None → 0 (flash), 2048 (pro).

    Returns:
        Time-ordered list of LabelApplication.
    """
    from google import genai

    video_path = Path(video_path)
    if not video_path.exists():
        raise FileNotFoundError(video_path)

    api_key = os.environ.get("GOOGLE_AI_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_AI_API_KEY not set")

    model_name = model or GEMINI_MODEL_DEFAULT
    if thinking_budget is None:
        thinking_budget = 0 if "flash" in model_name.lower() else 2048

    if cache_dir is None:
        cache_dir = video_path.parent / "cache" / video_path.stem
    cache_dir.mkdir(parents=True, exist_ok=True)

    duration = _probe_duration(video_path)
    if verbose:
        print(f"  {video_path.name}: duration={duration:.1f}s, model={model_name}",
              flush=True)

    # 1. Audio (cached)
    audio_path = _extract_audio(video_path, cache_dir)
    audio_bytes = audio_path.read_bytes()
    if verbose:
        print(f"  audio: {len(audio_bytes)/1024:.0f}KB ({audio_path.name})",
              flush=True)

    # 2. Frames (base + scene-cut supplemental)
    base_frames = _sample_frames_at_interval(video_path, sample_interval, cache_dir)
    scene_cuts = _detect_scene_cuts(video_path, scene_threshold)
    supp_frames = _extract_scene_cut_supplemental_frames(
        video_path, scene_cuts, DEFAULT_SCENE_SUPPLEMENT_WINDOW, cache_dir,
    )
    frames = _merge_frame_lists(base_frames, supp_frames)
    if verbose:
        print(f"  frames: {len(base_frames)} base + {len(supp_frames)} scene-cut "
              f"→ {len(frames)} total; {len(scene_cuts)} scene cuts detected",
              flush=True)

    # 3. Whisper transcript (cached)
    transcript_cache = cache_dir / "transcript.json"
    words = _transcribe_with_whisper(audio_path, transcript_cache, verbose=verbose)
    transcript_text = _format_transcript_for_prompt(words)

    # 4. Chunked classification
    client = genai.Client(api_key=api_key)
    all_classifications = []
    total_in = 0
    total_out = 0
    n_chunks = (len(frames) + chunk_frames - 1) // chunk_frames
    for ci in range(n_chunks):
        chunk = frames[ci * chunk_frames : (ci + 1) * chunk_frames]
        if verbose:
            print(f"  chunk {ci+1}/{n_chunks}: {len(chunk)} frames...",
                  end="", flush=True)
        t0 = time.time()
        try:
            entries, in_tok, out_tok = _classify_frames_chunk(
                client, chunk, audio_bytes, transcript_text, scene_cuts,
                content_type, duration, model_name, thinking_budget,
            )
        except (RuntimeError, ValueError, json.JSONDecodeError) as e:
            if verbose:
                print(f" FAILED: {e}", flush=True)
            entries = []
            in_tok = out_tok = 0
        else:
            n_labels_this_chunk = sum(len(e.get("labels", [])) for e in entries)
            if verbose:
                print(f" {time.time()-t0:.0f}s, {in_tok:,} in / {out_tok:,} out "
                      f"({n_labels_this_chunk} labels)", flush=True)
        # Remap local frame_index → global frame_index
        for e in entries:
            try:
                local_idx = int(e.get("frame_index", 0))
            except (TypeError, ValueError):
                local_idx = 0
            e["frame_index"] = ci * chunk_frames + local_idx
        all_classifications.extend(entries)
        total_in += in_tok
        total_out += out_tok

    # 5. Merge per-frame labels into LabelApplication ranges
    apps = _merge_frame_labels_to_applications(
        all_classifications, frames, sample_interval, model_name,
    )
    # Clamp end_sec at duration
    for a in apps:
        if a.end_sec > duration:
            a.end_sec = round(duration, 3)

    if verbose:
        # Gemini pricing (verified 2026-04-22 from ai.google.dev/gemini-api/docs/pricing).
        # Audio input is billed at a higher rate than text/image/video input —
        # but API returns a single prompt_token_count, so we blend audio into
        # the text rate. Actual cost is typically 20-30% higher than this
        # estimate when audio is a significant share of input.
        rates = {
            "gemini-2.5-flash":        (0.30, 2.50),
            "gemini-3-flash-preview":  (0.50, 3.00),
            "gemini-2.5-pro":          (1.25, 10.00),
        }
        rate_in, rate_out = rates.get(model_name, (0.50, 3.00))
        cost = (total_in * rate_in + total_out * rate_out) / 1_000_000
        print(f"  {len(apps)} applications · {total_in:,} in / {total_out:,} out · "
              f"~${cost:.4f} (text-rate est; audio input is billed ~$1/MTok)",
              flush=True)

    return apps
